Universe              = vanilla
executable            = miniAOD_mcSkim.sh
arguments             = $(ProcId) 
GetEnv                = True
output                = condorLog/output/$(ClusterId).$(ProcId).out
error                 = condorLog/error/$(ClusterId).$(ProcId).err
log                   = condorLog/log/$(ClusterId).$(ProcId).log
#requirements 	      = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "longlunch"

queue 1
